services:
  postgres:
    image: postgres:16
    container_name: mosquizto_dbpg
    environment:
      POSTGRES_DB: mosquiztodb
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass321
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user123 -d mosquiztodb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: