spring:
  application:
    name: Mosquizto-Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mosquiztodb
    username: ${DB_USER:postgres} # Mặc định là postgres nếu ko có biến env
    password: ${DB_PASSWORD:Dat1101&}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    from: ${MAIL_ADDRESS:tandatthtt@gmail.com}
    username: ${MAIL_USERNAME:tandatthtt@gmail.com}
    password: ${MAIL_PASSWORD:ivvv pnre jzry jqrf}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiryHour: 1
  expiryDay: 14
  # Cần key tối thiểu 32 ký tự để không lỗi bảo mật
  accessKey: ${JWT_ACCESS_KEY:q1zVZyZ6u8X9mQf5bG2nYxJ3o4pT7wV9rKc8lM2hQ0s=}
  refreshKey: ${JWT_REFRESH_KEY:q1zVZyZ6u8X9mQf5bG2nYxJ3o4pT7wV9rKc8lM2hQ0s=}
  resetKey: ${JWT_RESET_KEY:q1zVZyZ6u8X9mQf5bG2nYxJ3o4pT7wV9rKc8lM2hQ0s=}

open-api:
  service:
    title: ${OPEN_API_TITLE:Mosquizto API Service}
    version: ${OPEN_API_VERSION:v1.0}
    server-url: ${SERVER_URL:http://localhost:8080/}
    server-name: ${SERVER_NAME:localhost}

endpoint:
  confirmUser: ${SERVER_URL:http://localhost:8080/}user/confirm