spring:
  application:
    name: Mosquizto-Backend

  datasource:
    url: jdbc:postgresql://localhost:5436/mosquiztodb
    username: user123
    password: pass321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    from: genpicturege@gmail.com
    username: genpicturege
    password: ytnutnqqwdlwyxzw
    host: smtp.gmail.com
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

open-api:
  service:
    title: Api Service
    version: v1.0
    server-url: http://localhost:8080/
    server-name: localhost

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: JT/tDvZO6dVigguT0KH46c3ReORHnmOUluglIdogCXw=
  refreshKey: HNkhDWCBoC7gCzCk44BZGsJ1CCqWZowXoKJFnT8EDww=
  resetKey: JT/tDvZO6dVigguT0KH46c3ReORHnmOUluglIdogCXw=

endpoint:
  confirmUser: http://localhost:8080/user/confirm